# Generated by Django 3.2 on 2021-04-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Depto', models.TextField()),
                ('Direc', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('piso', models.CharField(blank=True, max_length=20)),
                ('ambientes', models.CharField(blank=True, max_length=20)),
                ('toilet', models.CharField(blank=True, max_length=20)),
                ('metro_tot', models.CharField(blank=True, max_length=20)),
                ('precio', models.CharField(blank=True, max_length=20)),
                ('reference', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='users/pictures')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
