# Generated by Django 3.2 on 2021-04-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depto',
            old_name='ambientes',
            new_name='Ambientes',
        ),
        migrations.RenameField(
            model_name='depto',
            old_name='metro_tot',
            new_name='Baños',
        ),
        migrations.RenameField(
            model_name='depto',
            old_name='creado',
            new_name='Creado',
        ),
        migrations.RenameField(
            model_name='depto',
            old_name='Direc',
            new_name='Direccion',
        ),
        migrations.RenameField(
            model_name='depto',
            old_name='phone_number',
            new_name='Metros_Tot',
        ),
        migrations.RenameField(
            model_name='depto',
            old_name='modificado',
            new_name='Modificado',
        ),
        migrations.RenameField(
            model_name='depto',
            old_name='piso',
            new_name='Numero_Contacto',
        ),
        migrations.RenameField(
            model_name='depto',
            old_name='reference',
            new_name='Observaciones_visita',
        ),
        migrations.RenameField(
            model_name='depto',
            old_name='precio',
            new_name='Piso',
        ),
        migrations.RenameField(
            model_name='depto',
            old_name='toilet',
            new_name='Precio',
        ),
        migrations.RemoveField(
            model_name='depto',
            name='picture',
        ),
        migrations.AddField(
            model_name='depto',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='departamentos/pictures'),
        ),
    ]
