# Generated by Django 3.2 on 2021-04-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_auto_20210419_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='depto',
            name='Fecha_visita',
            field=models.DateField(null=True),
        ),
    ]
