# Generated by Django 3.2 on 2021-04-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_depto_fecha_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='depto',
            name='Contras',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='depto',
            name='Pros',
            field=models.TextField(blank=True),
        ),
    ]
